export const COMMAND_STATE = {
  PREPARED: 'PREPARED',
  REQUESTED: 'REQUESTED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
};

export const API_NAME = {
  GET_RESULTS: 'GET_RESULTS',
  GET_PROJECT: 'GET_PROJECT',
  GET_ITERATION: 'GET_ITERATION',
  GET_USECASE: 'GET_USECASE',
  GET_TRIAL: 'GET_TRIAL',
};
