export const COMMAND_STATE = {
  PREPARED: 'PREPARED',
  REQUESTED: 'REQUESTED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
};

export const API_NAME = {
  GET_USECASES: 'GET_USECASES',
  ADD_USECASE: 'ADD_USECASE',
  MODIFY_USECASE: 'MODIFY_USECASE',
  DELETE_USECASE: 'DELETE_USECASE',
  GET_TRIALS: 'GET_TRIALS',
  ADD_TRIAL: 'START_TRIAL',
  GET_RESULT: 'GET_RESULT',
};
