export const COMMAND_STATE = {
  PREPARED: 'PREPARED',
  REQUESTED: 'REQUESTED',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
};

export const API_NAME = {
  ADD_USECASE: 'ADD_USECASE',
  MODIFY_USECASE: 'MODIFY_USECASE',
  DELETE_USECASE: 'DELETE_USECASE',
};
